POST http://127.0.0.1:5000/service_hub/settings/loglevel/database HTTP/1.1
content-type: application/json

{
    "value": 2
}


GET http://127.0.0.1:5000/service_hub/settings/loglevel/database HTTP/1.1